# Netlify Configuration
# Frontend Only Deployment

[build]
  # Client klasöründen build yap
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Secrets scanning - sadece dokümantasyon ve example dosyalarını hariç tut
  SECRETS_SCAN_OMIT_PATHS = "*.md,*.example,client/.env.example,backend/.env.example,.netlify/**"

# SPA routing için - tüm route'ları index.html'e yönlendir
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Performance - Static dosyalar için cache
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
